development:
  adapter: postgresql
  database: shajith_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: shajith_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: shajith_production
  pool: 5
  timeout: 5000
